### ISSUE TITLE
Rare or situational bug with the `spsc_queue_unsafe` ? 

### ISSUE THREAD

**Issue by lyrm** [ocaml-multicore/saturn#144]
While working on PR #143, I encountered the same test failing twice in a row (see picture below). I have not been able to reproduce it since.

![Screenshot from 2024-07-04 14-07-37](https://github.com/ocaml-multicore/saturn/assets/8844397/eb095a54-5169-4aeb-93b4-7dfac7715099)

**Comment by polytypic** [comment]
Hmm... Both `peek` and `pop` should only be called by the consumer on a SPSC queue.  So, the test is trying to do illegal things.

**Comment by lyrm** [comment]
This is actually a negative test, that is supposed to fail !
