### ISSUE TITLE
Keeping the README updated

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/saturn#20]
May I suggest that we keep the README updated as we include additional lockfree data structures. When README goes out of sync with the code, it is harder for someone else to come in later to add context compared to the original author editing the README. Someone needs to fix the README now that we have an MPSC queue in the library and the README is out of sync. Perhaps @lyrm can do it since they'd contributed the MPSC queue? 

Separately, given that there will be plenty of different queues with different restrictions, it would be better if README actually explains the tradeoffs between them (number of producers, number of consumers, bounded or not, aligned or not, etc). I would go so far as to say that new lock-free data structures proposed to be added to the library should be rejected if they don't explain where they sit in relation to the other data structures in the library. This information should be reflected in the README so that users have all the information to make sensible decisions.

**Comment by lyrm** [comment]
You are absolutely right. I should and will update the README to include the new data structures. 

For the second part: yes, this is the plan. I will add in the next README update these kinds of information for the current data structures. 

In a near future, I also intend to have some  benchmarks as data structures may have a "better use case"  (depending on write/read load, in particular).

**Comment by Sudha247** [comment]
#91 addresses this.
