### ISSUE TITLE
Single core benchmarks

### ISSUE THREAD

**Issue by lyrm** [ocaml-multicore/saturn#56]
This library lacks some single core benchmarks  to compare its domain safe data structures to the standard library data structures (that are not thread safe). This idea is to measure the overhead paid for lock-freedom  and multi-domain safety.

| Lockfree data structures | Standard library data structures     | 
|-------------|------------|
| [Michael-Scott queue]( https://github.com/ocaml-multicore/lockfree/blob/main/src/michael_scott_queue.mli )  | [Stdlib.Queue](https://v2.ocaml.org/api/Queue.html) |
| [Mpmc queue](https://github.com/ocaml-multicore/lockfree/blob/main/src/mpsc_queue.mli) |  [Stdlib.Queue](https://v2.ocaml.org/api/Queue.html) | 
| [Spsc queue](https://github.com/ocaml-multicore/lockfree/blob/main/src/spsc_queue.mli) |  [Stdlib.Queue](https://v2.ocaml.org/api/Queue.html) |
| [Working stealing dequeue](https://github.com/ocaml-multicore/lockfree/blob/main/src/ws_deque.mli) |  [Core.Deque](https://ocaml.janestreet.com/ocaml-core/109.55.00/tmp/core_kernel/Dequeue.html) |
|  [Treiber stack](https://github.com/ocaml-multicore/lockfree/blob/main/src/treiber_stack.mli) | [Stdlib.Stack](https://v2.ocaml.org/api/Stack.html) |

**Comment by Vincent-lau** [comment]
Hi I have run some simple benchmarks by extending the `bench_queue.ml` for comparsion of lock free queues and the standard library queues. Here are the results

```
Saturn_lockfree Queue:
  time per message/one domain:
    75.12 ns
  messages over time/one domain:
    13.31 M/s
  time per message/1 nb adder, 1 nb taker:
    240.00 ns
  messages over time/1 nb adder, 1 nb taker:
    8.33 M/s
  time per message/1 nb adder, 2 nb takers:
    378.39 ns
  messages over time/1 nb adder, 2 nb takers:
    7.93 M/s
  time per message/2 nb adders, 1 nb taker:
    212.92 ns
  messages over time/2 nb adders, 1 nb taker:
    14.09 M/s
  time per message/2 nb adders, 2 nb takers:
    296.55 ns
  messages over time/2 nb adders, 2 nb takers:
    13.49 M/s
Stdlib Queue:
  time per message/one domain:
    27.04 ns
  messages over time/one domain:
    36.98 M/s

```
