### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by lyrm** [ocaml-multicore/saturn#57]
This library is currently lacking documentation. A good step will be to add simple examples (with multiple domains) for each data structures that could serve as tutorial.  

More complex examples would also be great, in particular for testing purposes.

**Comment by nikochiko** [comment]
Hey I'd like to take this up.
I've been going through the MS queue paper and I have a fair of that and other lockfree structures now.

Where should the examples go? The README or a separate examples/ directory?

**Comment by Sudha247** [comment]
Hey @nikochiko, thanks for your interest! MSQueue is a good one to start with. The examples can go to a new `examples` directory.

**Comment by lyrm** [comment]
This has been done in recent PR for all data structures.
