### ISSUE TITLE
Ocaml CI `lint-lower-bounds` failing

### ISSUE THREAD

**Issue by lyrm** [ocaml-multicore/saturn#73]
Currently,  Ocaml CI always fails its `lint-lower-bounds` check with an `Out of memory` exception.  

![Screenshot from 2023-05-17 15-46-09](https://github.com/ocaml-multicore/lockfree/assets/8844397/9ecf9ac5-e0b4-44a7-ac33-748198f15881)

It will probably be fixed by a future `dscheck` release. If not, this will need to be investigated.

**Comment by Sudha247** [comment]
I don't see this issue in the recent ocaml-ci runs. Perhaps the new dscheck release fixed it. Closing this.
