### ISSUE TITLE
Lock-based Skiplist implementation

### ISSUE THREAD

**Issue by koonwen** [ocaml-multicore/saturn#87]
Hi there! I notice that `saturn` is now accepting locked-based concurrent data structures. I happen to have a Lazy Skiplist implemented according to _The Art of Multiprocessor Programming section 14.3_ from a previous project. It's been moderately bench marked showing good scaling properties as number of domains increase. Thread safety also seems to be preserved from my testing.

Am wondering if there's any interest in adding it to this library before I start trying to port it here. Have a first look [here](https://github.com/koonwen/obatcher/blob/b368494071d1c7c93c81a5e00acfaadf1506a4cb/ds/utils.ml#L187-L370)

**Comment by lyrm** [comment]
Hi! I will have a proper look next week ! Thanks for sharing your work. 

After a very (very) quick look, and as we are trying to avoid adding dependencies, I am wondering : would your implementation work well without `batteries` (with the adequate changes, obviously) ?

**Comment by koonwen** [comment]
So I've used `batteries` just for the Re-entrant Mutex because it's not available in the Stdlib. I had a look into how it's implemented there and seems like it could be moved into `saturn` without introducing additional dependencies. Let me play around with it over the weekend and update again if it works.

**Comment by lyrm** [comment]
I should add that we already have a lockfree `skiplist` implementation (PR #65) waiting for (me to do) improvements (like adding polymorphism) and (then) a proper review.

I am however very interested in seeing how the (final version of those) skiplist algorithms compared in different cases of uses !

**Comment by koonwen** [comment]
Owing to the sharp observation by @polytypic that the current implementation of the Re-entrant Mutex [is incompatible](https://github.com/ocaml-multicore/saturn/pull/90#discussion_r1278890716) with effect-based schedulers and no straightforward solution exists yet. Should we close this or is it still worth building even with constraints on when it can be used?

**Comment by polytypic** [comment]
> Should we close this or is it still worth building even with constraints on when it can be used?

Let's not be hasty.  The issues with Stdlib locks and blocking primitives in general has been known for a long time already and it is something we do plan to work on.  So, unless you have some sort of deadline then I wouldn't recommend to close the PR.  We should be able to review the code otherwise even without the scheduler friendly primitives and can then update it to use those when such primitives exist.

**Comment by lyrm** [comment]
Thanks for the issue and the work. I have closed the PR as we are not moving in this direction and thus I am also closing this issue.
