### ISSUE TITLE
Import `kcas_data` as a part of `saturn`

### ISSUE THREAD

**Issue by Sudha247** [ocaml-multicore/saturn#93]
[kcas_data](https://github.com/ocaml-multicore/kcas/tree/main/src/kcas_data) contains a nice set of compositional lock-free structures built with `kcas`. This is in alignment with the goal of `saturn`, to provide parallelism-safe data structures for OCaml 5+ users. It might be useful to expose these structures in `kcas_data` as a part of `saturn_lockfree` or even a separate sub-package.

cc @polytypic @lyrm

**Comment by lyrm** [comment]
This plan has been cancelled.
